# Generated by Django 4.1.4 on 2023-05-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_subject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
    ]
