# Generated by Django 4.1.4 on 2023-05-29 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_classes_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
