# Generated by Django 4.1.4 on 2023-06-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ansewr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansewr',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.homework'),
        ),
    ]
