# Generated by Django 4.1.4 on 2023-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ansewr_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл задания'),
        ),
    ]
