# Generated by Django 4.1.4 on 2023-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ansewr_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл задания'),
        ),
    ]
