# Generated by Django 4.1.4 on 2023-06-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_name_homework_homework_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homework_name',
            new_name='name',
        ),
    ]
