# Generated by Django 4.1.4 on 2023-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.IntegerField(null=True, unique=True, verbose_name='Номер телефона')),
                ('school', models.CharField(blank=True, default='блять', max_length=60, verbose_name='Школа')),
                ('gender', models.CharField(choices=[('man', 'мужской'), ('woman', 'женский')], default=('man', 'мужской'), max_length=7, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Фото профиля')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('type_of_user', models.CharField(choices=[('pupil', 'Ученик'), ('teacher', 'Учитель'), ('parent', 'Родитель')], default=('pupil', 'Ученик'), max_length=8, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
