# Generated by Django 4.1.4 on 2023-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_subject_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classess',
            field=models.ManyToManyField(blank=True, to='main.classes'),
        ),
    ]
