# Generated by Django 4.1.4 on 2023-01-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('pupil', 'Ученик'), ('teacher', 'Учитель'), ('parent', 'Родитель')], default=('pupil', 'Ученик'), max_length=8, verbose_name='Роль'),
        ),
    ]
